### PR TITLE
Modifications to tie this code into the DMPTool Rails app

### PR DESCRIPTION
**Pull request by briri**
Updated the DMPTool Rails code to see how we can server up the React UI from within the Rails context. You can see the corresponding changes I needed to make to Rails in [this PR](https://github.com/CDLUC3/dmptool/pull/478). I'm happy to report they were pretty minimal.

- For some reason I had to add an import for `React` in all the js files. I might be able to just place that import into the Rails application's new `react-application.js` file before I import the `dmp-hub-ui/index.js`. Perhaps I need to add the contents of your package.json to the Rails' app package.json. I am open to suggestions though :)
- Updated the router to default to `/dashboard` since `/` is taken in the Rails app
- Updated the dashboard to display a 'Welcome back [User Name]` name message to illustrate that we were able to fetch this info from the API.
- I had to hard code the stuff happening in `utils.js` because I was getting an error about `arguments[key].clone is not a function` and did not have time to investigate it.
- I just stubbed in the TEST_TOKEN value rather than add a `tmp.js` to my Rails app deploy since I don't think we need that long term. The `1111111111` is a throw away key, so no worries there

We will need to find a way to pull the API_BASE_URL in from the Rails app. Not sure of the best way to do that. Can it be passed in to the initialization of the React App? 

I am reconsidering some of the API now that I've done this work. I am going to move many of the API endpoints directly into the Rails application and will then create proxy endpoints within the Rails app that call out to other endpoints that do actually need to live in the new Lambdas. For example, the `/wips` endpoints access the Rails DB, so it makes sense to just put them in the Rails app for now. The `/dmps` endpoints however work with AWS resources not accessible by the Rails app, so I will build proxy endpoints in the Rails app that deal with user auth (etc.) and then make calls to the AWS API. I think that will also be much much easier for the development of the React app. Let me know what you think though.

We should also discuss how best to manage the code going forward. There may no longer be value to keeping the changes in this repo. There are pros and cons to that though, so lets discuss on Slack next week

You can see this all running by logging into https://dmptool-stg.cdlib.org and then clicking on the 'Prototype Dashboard' button that appears on the top right of the Dashboard page when you login.

### CODE REVIEW

**Comment by andrewebdev** [comment]
Looking at the dashboard code you have, the reason you had errors is most likely because it was based off an old commit. Could you rebase or merge my branch first?

Then have a look at my dashboard code and how it uses the utility functions to make api requests more consistent. The api path should rather not be hardcoded for every single request, for example.

I noticed that you also made requests to your localhost. I'm assuming that's because your ruby test backend is running there? If so, we can potentially add an environment setting that we can use to override the api path for testing?

**Comment by briri** [comment]
I pulled down your latest and it's still throwing that error when I try to call a function in utils.js. My guess is that it's the way Rails is building the React code.

Rails is using Yarn and Webpack to manage its assets. The web pack config is here:
- [Webpack config](https://github.com/CDLUC3/dmptool/blob/react-as-git-module/config/webpack/webpack.config.js)
- [The package.json](https://github.com/CDLUC3/dmptool/blob/react-as-git-module/package.json)

When Rails runs `rails assets:precompile` it's using that web pack config and yarn to install and manage dependencies. By default it builds a minified `application-[fingerprint].js` file that is then included into the HTML when the Rails engine builds the page. 

Since there is so much other junk that the existing Rails app is using (e.g. jQuery and Bootstrap), I decided to add another entry point to the web pack config so that it would just use the dependencies that you need for the React app. Rails picks up [this JS file](https://github.com/CDLUC3/dmptool/blob/react-as-git-module/app/javascript/react-application.js) and then builds a `react-application-[fingerprint].js` that gets is included into the page in this [Rails layout template](https://github.com/CDLUC3/dmptool/blob/react-as-git-module/app/views/branded/layouts/react_application.html.erb).

As you can see in [that JS file](https://github.com/CDLUC3/dmptool/blob/react-as-git-module/app/javascript/react-application.js), I added `window.React = React;` and I stopped needing to add an `import React from 'react';` to every file.

Maybe I just need to add more of them to `window.` for it to work or ... maybe I need to wrap the index.js code in a document ready block?

**Not expecting you guys to work on the weekend! Waiting until Monday is 100% ok!**

**Comment by andrewebdev** [comment]
@briri _Regarding passing the api base url to the React application_; Yes, this can probably be done by something as simple as adding a script with a global constant in `react_application.html.erb`. Something like:

```html
<script>
    const API_BASE_URL = "https://api.dmphub-dev.cdlib.org";
</script>
```

Now I personally prefer to add Global Config, settings and functions inside an `app` object that I attach to the html document directly. This way it's a bit more confined. I do this typically like this:
```javascript
document.webapp = new MyApp({
    apiBaseUrl: "https://api.dmphub-dev.cdlib.org";
});
```

The former is obviously the easier way, because there is very little extra coding. The latter require a bit more work, but you can add application specific code, like initialization directly to the `MyApp` class. From there it can always be accessed via: `document.webapp.api_path('dmps')`, for example.

We can probably move all the utils.py code into the application object, should we choose the latter approach.

**Comment by briri** [comment]
closing as this repo is no longer applicable

**Pull request closed without merging**
